# - name: Executable is present
#   get_url:
#     url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
#     dest: /usr/local/bin/docker-compose
#     mode: 0755
#   tags: [docker-compose]

- name: docker-compose is present
  pip:
    name: docker-compose
    state: present
  tags: [docker-compose]
