- name: DockerUI is running
  docker:
    image: uifd/ui-for-docker
    name: dockerui
    privileged: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  when: not skip_ui is defined
  tags: [docker]
