- name: Certbot repository is present
  apt_repository: 
    repo: 'deb http://ftp.debian.org/debian jessie-backports main' 
    state: present

- name: Certbot is present
  apt: 
    name: certbot
    state: installed
    update_cache: yes
    default_release: jessie-backports

